//
//  SeedData.swift
//  Bearing Atlas Pro
//
//  Fixed engineering content for the 20 locked faults.
//  Each fault has exactly one knowledge article and one maintenance task,
//  all linked by fault id (1-based, matching insertion order).
//  English only. No free text — every field is populated.
//

import Foundation

enum BAEPSeedData {

    // (name, system, severity, description) — order defines fault id 1...20
    static let faults: [(String, String, String, String)] = [
        ("Motor Overheating", "Induction Motor", "High", "Excess temperature rise"),
        ("Bearing Outer Race Fault", "Bearing System", "High", "Outer race damage"),
        ("Bearing Inner Race Fault", "Bearing System", "High", "Inner race failure"),
        ("Rotor Imbalance", "Rotor System", "Medium", "Mass imbalance"),
        ("Stator Winding Failure", "Electrical System", "Critical", "Insulation failure"),
        ("Voltage Phase Imbalance", "Electrical System", "High", "Uneven phase voltage"),
        ("Phase Loss", "Electrical System", "Critical", "Missing phase"),
        ("Motor Not Starting", "Induction Motor", "High", "No rotation"),
        ("Low Speed", "Drive System", "Medium", "Below rated speed"),
        ("Cooling Fan Failure", "Cooling System", "High", "No airflow"),
        ("Lubrication Failure", "Bearing System", "High", "Insufficient lubrication"),
        ("Excessive Vibration", "Mechanical System", "High", "High vibration level"),
        ("Shaft Misalignment", "Mechanical System", "High", "Misaligned shaft"),
        ("Insulation Breakdown", "Electrical System", "Critical", "Dielectric failure"),
        ("High Starting Current", "Electrical System", "High", "Excess inrush current"),
        ("Unbalanced Load", "Mechanical System", "Medium", "Uneven load"),
        ("Loose Mounting Base", "Mechanical System", "Medium", "Loose foundation"),
        ("Rotor Bar Damage", "Rotor System", "High", "Broken rotor bars"),
        ("Contactor Failure", "Control System", "Medium", "Switching fault"),
        ("Bearing Overheating", "Bearing System", "High", "Thermal bearing failure"),
    ]

    // Knowledge article per fault id (faultId, title, overview, causes, symptoms, inspection, maintenance)
    static let articles: [(Int, String, String, String, String, String, String)] = [
        (1, "Motor Overheating",
         "Temperature rise beyond the insulation class rating accelerates winding degradation and shortens motor life.",
         "Sustained overload; blocked ventilation; high ambient temperature; voltage imbalance; excessive start/stop cycles.",
         "Casing too hot to touch; thermal trip events; burnt insulation odor; reduced output torque.",
         "Measure winding temperature with IR camera. Verify load current vs nameplate. Inspect cooling path for blockage.",
         "Reduce load to rated value, clear ventilation paths, correct supply voltage, and re-test temperature under load."),
        (2, "Bearing Outer Race Fault",
         "Localized damage on the stationary outer race generates impacts at the ball-pass outer-race frequency (BPFO).",
         "Contamination; fatigue spalling; improper fit in housing; false brinelling from vibration at standstill.",
         "Periodic broadband noise; vibration peak at BPFO; intermittent rumble that worsens under load.",
         "Capture vibration spectrum and confirm BPFO harmonics. Listen with stethoscope. Inspect race on removal.",
         "Replace the bearing, verify housing fit and tolerance, re-lubricate, and confirm vibration falls below alarm."),
        (3, "Bearing Inner Race Fault",
         "Damage on the rotating inner race produces impacts modulated by shaft speed at the ball-pass inner-race frequency (BPFI).",
         "Misalignment loading; contamination; loss of lubricant film; overheating-induced hardness loss.",
         "Sidebands around BPFI spaced at run speed; rising temperature; cyclic vibration tied to rotation.",
         "Analyze spectrum for BPFI plus run-speed sidebands. Check shaft temperature. Inspect inner race after pull.",
         "Replace bearing, correct alignment, restore lubrication schedule, and verify spectrum is clean post-repair."),
        (4, "Rotor Imbalance",
         "Uneven mass distribution about the rotation axis creates a centrifugal force once per revolution.",
         "Material buildup or loss; bent shaft; loose components; manufacturing tolerance; corrosion.",
         "Strong 1x run-speed vibration; vibration scales with speed squared; even radial vibration around housing.",
         "Measure 1x amplitude and phase. Confirm dominance at run speed. Inspect rotor for debris or damage.",
         "Clean rotor, perform field or shop balancing to ISO grade, retighten components, and re-measure 1x level."),
        (5, "Stator Winding Failure",
         "Breakdown of winding insulation allows turn-to-turn or phase-to-ground short circuits.",
         "Thermal aging; moisture ingress; voltage surges; contamination; mechanical abrasion of insulation.",
         "Tripped protection; phase current imbalance; burnt smell; low insulation resistance reading.",
         "Perform insulation resistance and polarization index tests. Surge-test windings. Inspect for discoloration.",
         "Rewind or replace stator, dry and re-varnish if salvageable, address moisture source, and re-test insulation."),
        (6, "Voltage Phase Imbalance",
         "Unequal phase voltages cause negative-sequence currents that heat the motor disproportionately.",
         "Unbalanced single-phase loads on supply; loose connections; failing transformer tap; utility imbalance.",
         "Elevated winding temperature; current imbalance exceeding voltage imbalance; nuisance overload trips.",
         "Measure all three line-to-line voltages. Compute percent imbalance. Inspect connections for resistance.",
         "Rebalance distribution loads, tighten and clean terminals, correct supply source, and verify imbalance under 1%."),
        (7, "Phase Loss",
         "Loss of one supply phase forces single-phase operation, overheating remaining windings rapidly.",
         "Blown fuse; open contactor pole; broken conductor; loose terminal opening under load.",
         "Motor stalls or fails to start; loud hum; rapid overheating; two-phase current with one near zero.",
         "Measure all three phase currents and voltages. Identify the open phase. Inspect fuses and contactor poles.",
         "Restore the lost phase, replace failed fuse or contactor, verify balanced three-phase current, then restart."),
        (8, "Motor Not Starting",
         "The motor fails to develop starting torque or receives no energization.",
         "Control circuit fault; seized bearing; phase loss; open winding; mechanical lock of driven load.",
         "No rotation on command; humming without motion; tripped protection; no current draw.",
         "Verify control voltage at the motor terminals. Check rotor freedom by hand. Test windings for continuity.",
         "Restore supply or repair control circuit, free the seized component, repair winding, and confirm clean start."),
        (9, "Low Speed",
         "The motor runs below rated speed, indicating excessive slip or supply deficiency.",
         "Overload; low or unbalanced voltage; rotor bar damage; incorrect drive frequency setting.",
         "Output below target; high slip; elevated current; reduced process throughput.",
         "Measure shaft speed with tachometer. Compare supply voltage and frequency to nameplate. Check load torque.",
         "Reduce load, correct supply voltage and frequency, repair rotor if needed, and verify rated speed restored."),
        (10, "Cooling Fan Failure",
         "Loss of forced airflow removes the motor's primary heat rejection path, driving overheating.",
         "Broken or loose fan; cracked hub; debris jam; cowling blockage; corrosion of blades.",
         "Rising temperature with normal load; no airflow at outlet; rattling from fan end; thermal trips.",
         "Inspect fan blades and hub for damage. Confirm airflow at the cowling. Check for obstructions.",
         "Replace the fan, clear the cowling and air path, secure the hub, and verify airflow and steady temperature."),
        (11, "Lubrication Failure",
         "Insufficient or degraded lubricant collapses the bearing film, causing metal-to-metal contact.",
         "Missed regreasing; wrong grease type; over-greasing; contamination; seal failure.",
         "Rising bearing temperature; high-frequency vibration; squealing; grease discoloration.",
         "Check grease condition and quantity. Measure bearing temperature. Review lubrication interval records.",
         "Purge and replace with the specified grease at correct volume, repair seals, and set the regreasing schedule."),
        (12, "Excessive Vibration",
         "Vibration above alarm thresholds indicates a developing mechanical or electrical fault.",
         "Imbalance; misalignment; looseness; bearing defect; resonance; electrical asymmetry.",
         "Amplitude over ISO limits; audible roughness; fastener loosening; secondary component fatigue.",
         "Acquire a full vibration spectrum and overall level. Identify dominant frequency and phase. Check mounting.",
         "Correct the root cause (balance, align, tighten, or replace bearing) and re-measure against ISO limits."),
        (13, "Shaft Misalignment",
         "Angular or parallel offset between driver and driven shafts imposes cyclic bending and radial loads.",
         "Poor installation; thermal growth; soft foot; pipe strain; settled foundation.",
         "Strong 2x run-speed vibration; high axial vibration; coupling wear; bearing heat.",
         "Perform laser or dial-indicator alignment. Check soft foot. Inspect coupling condition.",
         "Realign to manufacturer tolerance, correct soft foot and strain, replace worn coupling, and re-verify alignment."),
        (14, "Insulation Breakdown",
         "Dielectric failure of insulation permits leakage or flashover to ground.",
         "Moisture; thermal aging; partial discharge; contamination; mechanical damage.",
         "Low insulation resistance; ground faults; tracking marks; tripped earth-leakage protection.",
         "Run insulation resistance and high-potential tests. Inspect for tracking and carbonization.",
         "Dry, clean, and re-varnish or rewind as required, eliminate moisture ingress, and re-test to acceptance."),
        (15, "High Starting Current",
         "Inrush current exceeds expected levels, stressing supply and protection devices.",
         "Direct-on-line start of large motor; low voltage; mechanical overload at start; rotor fault.",
         "Voltage dip on start; nuisance breaker trips; prolonged inrush duration; contactor stress.",
         "Record start current profile with a clamp meter. Verify supply capacity. Check starting load.",
         "Apply soft start or star-delta, stiffen supply, reduce starting load, and confirm inrush within limits."),
        (16, "Unbalanced Load",
         "Uneven mechanical loading produces fluctuating torque and asymmetric heating.",
         "Uneven driven process; coupling defect; partial blockage; variable demand.",
         "Fluctuating current; cyclic vibration; localized heating; inconsistent output.",
         "Monitor current and torque variation over a cycle. Inspect the driven equipment for uneven load.",
         "Balance the mechanical load, repair the coupling, clear blockages, and verify steady current and vibration."),
        (17, "Loose Mounting Base",
         "A loose foundation lets the machine move under operating forces, amplifying vibration.",
         "Loose hold-down bolts; cracked or grouted base; corrosion; foundation settlement.",
         "High vibration at run speed and harmonics; directional looseness; bolt fretting; shifting feet.",
         "Check bolt torque and base flatness. Look for cracks and fretting. Measure motion at feet.",
         "Retorque or replace fasteners, repair or regrout the base, correct soft foot, and re-measure vibration."),
        (18, "Rotor Bar Damage",
         "Broken or cracked rotor bars disrupt the rotor current path and torque production.",
         "Thermal cycling; casting voids; mechanical stress; frequent heavy starts.",
         "Pole-pass sidebands around line frequency; speed fluctuation; reduced torque; current modulation.",
         "Perform current signature analysis for pole-pass sidebands. Inspect rotor bars and end rings.",
         "Repair or replace the rotor, reduce start frequency, address thermal stress, and verify clean current signature."),
        (19, "Contactor Failure",
         "A failed contactor interrupts or chatters the supply path to the motor.",
         "Welded or pitted contacts; coil failure; mechanical wear; control voltage loss.",
         "Failure to energize; chattering; phase loss through one pole; arcing and heat at contacts.",
         "Inspect contacts for pitting. Measure coil voltage and resistance. Check pole continuity under load.",
         "Replace the contactor, verify control voltage, confirm all poles close cleanly, and test motor energization."),
        (20, "Bearing Overheating",
         "Excess bearing temperature degrades lubricant and hardness, leading to seizure if unchecked.",
         "Overload; misalignment; lubrication fault; excessive preload; contamination.",
         "Bearing housing too hot to touch; discolored grease; rising vibration; eventual seizure.",
         "Measure bearing temperature trend. Check alignment and lubrication. Inspect for preload and contamination.",
         "Correct lubrication and alignment, relieve preload, replace damaged bearing, and verify stable temperature."),
    ]

    // Maintenance task per fault id (faultId, name, tools, safety, steps, expectedResult)
    static let tasks: [(Int, String, String, String, String, String)] = [
        (1, "Restore Thermal Operation",
         "IR thermometer, clamp meter, cleaning brush, torque wrench.",
         "Lock out and tag out. Allow motor to cool. Wear insulated gloves when checking terminals.",
         "1. Verify load current against nameplate.\n2. Clear all ventilation and cooling paths.\n3. Correct supply voltage imbalance.\n4. Re-run under load and log temperature.",
         "Winding temperature stabilizes within the insulation class rating under rated load."),
        (2, "Replace Outer-Race Bearing",
         "Bearing puller, induction heater, vibration analyzer, dial gauge.",
         "Isolate and lock out power. Support the rotor. Use eye protection during pulling.",
         "1. Capture baseline vibration (BPFO).\n2. Remove and inspect the bearing.\n3. Verify housing fit and tolerance.\n4. Install and lubricate new bearing.\n5. Re-measure vibration.",
         "Vibration at BPFO falls below the alarm threshold and housing fit is within tolerance."),
        (3, "Replace Inner-Race Bearing",
         "Bearing puller, induction heater, vibration analyzer, alignment tool.",
         "Lock out and tag out. Support shaft weight. Avoid open flame near grease.",
         "1. Record BPFI spectrum and sidebands.\n2. Pull and inspect the bearing.\n3. Correct shaft alignment.\n4. Fit and grease the new bearing.\n5. Confirm clean spectrum.",
         "BPFI harmonics are eliminated and bearing temperature returns to normal."),
        (4, "Balance Rotor",
         "Balancing instrument, trial weights, scale, torque wrench.",
         "Isolate power and lock out. Secure guards before any test run. Stand clear during rotation.",
         "1. Measure 1x amplitude and phase.\n2. Clean debris from the rotor.\n3. Add or remove correction weights.\n4. Retighten all components.\n5. Re-measure 1x level.",
         "1x run-speed vibration is reduced to within the target ISO balance grade."),
        (5, "Repair Stator Winding",
         "Insulation tester, surge tester, varnish, oven, multimeter.",
         "De-energize and verify zero voltage. Discharge windings. Use respirator near varnish fumes.",
         "1. Test insulation resistance and PI.\n2. Surge-test for turn faults.\n3. Rewind or replace the stator.\n4. Dry and re-varnish.\n5. Re-test insulation.",
         "Insulation resistance and polarization index meet acceptance values."),
        (6, "Correct Voltage Imbalance",
         "Multimeter, clamp meter, torque wrench, thermal camera.",
         "Work on supply only with proper PPE and lockout. Verify de-energization before touching terminals.",
         "1. Measure all line-to-line voltages.\n2. Compute percent imbalance.\n3. Rebalance single-phase loads.\n4. Tighten and clean terminals.\n5. Re-measure imbalance.",
         "Voltage imbalance is reduced below 1% and current imbalance normalizes."),
        (7, "Restore Lost Phase",
         "Multimeter, clamp meter, fuse puller, replacement fuses/contactor.",
         "Lock out and tag out before opening enclosures. Verify zero voltage with a meter.",
         "1. Measure all three phase currents.\n2. Identify the open phase.\n3. Replace failed fuse or contactor pole.\n4. Verify balanced current.\n5. Restart and monitor.",
         "All three phases carry balanced current and the motor runs normally."),
        (8, "Diagnose No-Start",
         "Multimeter, megohmmeter, hand tools, control wiring diagram.",
         "Lock out power. Verify control circuit de-energized before probing. Keep hands clear of the shaft.",
         "1. Confirm control voltage at terminals.\n2. Rotate the shaft by hand.\n3. Test windings for continuity.\n4. Repair the identified fault.\n5. Attempt a controlled start.",
         "The motor starts on command and reaches rated speed without protection trips."),
        (9, "Recover Rated Speed",
         "Tachometer, multimeter, clamp meter, drive interface tool.",
         "Lock out before mechanical checks. Use PPE when measuring live circuits.",
         "1. Measure shaft speed.\n2. Compare voltage and frequency to nameplate.\n3. Reduce excess load.\n4. Correct supply or drive settings.\n5. Re-verify speed.",
         "Shaft speed returns to within the rated tolerance under normal load."),
        (10, "Replace Cooling Fan",
         "Screwdriver set, puller, replacement fan, cleaning brush.",
         "Isolate and lock out power. Wait for full stop. Wear gloves around blade edges.",
         "1. Remove the fan cowling.\n2. Inspect and remove the damaged fan.\n3. Clear the air path of debris.\n4. Fit and secure the new fan.\n5. Confirm airflow and temperature.",
         "Forced airflow is restored and motor temperature remains stable under load."),
        (11, "Restore Lubrication",
         "Grease gun, specified grease, cleaning rags, thermometer.",
         "Lock out power. Clean fittings before greasing. Avoid mixing incompatible greases.",
         "1. Inspect grease condition and amount.\n2. Purge old or contaminated grease.\n3. Add the specified grease volume.\n4. Repair failed seals.\n5. Set the regreasing interval.",
         "Bearing temperature and vibration return to normal and a lubrication schedule is set."),
        (12, "Reduce Vibration",
         "Vibration analyzer, alignment tool, torque wrench, balancing kit.",
         "Lock out before contact work. Secure guards before test runs. Stand clear during rotation.",
         "1. Acquire spectrum and overall level.\n2. Identify the dominant fault frequency.\n3. Apply the matching correction.\n4. Retighten mounting.\n5. Re-measure against ISO limits.",
         "Overall vibration level falls within ISO limits for the machine class."),
        (13, "Align Shafts",
         "Laser alignment tool or dial indicators, shims, torque wrench.",
         "Lock out and tag out. Allow thermal cool-down for cold alignment. Use PPE.",
         "1. Check and correct soft foot.\n2. Measure angular and parallel offset.\n3. Add or remove shims.\n4. Tighten to spec and recheck.\n5. Replace worn coupling.",
         "Alignment is within manufacturer tolerance and axial vibration is reduced."),
        (14, "Restore Insulation Integrity",
         "Megohmmeter, hipot tester, varnish, drying oven.",
         "De-energize and discharge. Barricade during hipot testing. Use respirator near varnish.",
         "1. Run insulation resistance and hipot tests.\n2. Locate tracking or carbonization.\n3. Dry and clean the windings.\n4. Re-varnish or rewind.\n5. Re-test to acceptance.",
         "Insulation passes resistance and hipot acceptance with no tracking."),
        (15, "Limit Starting Current",
         "Clamp meter with inrush capture, soft starter or star-delta gear, hand tools.",
         "Lock out before wiring changes. Verify zero voltage. Follow starter wiring diagram.",
         "1. Record the start current profile.\n2. Verify supply capacity.\n3. Install soft start or star-delta.\n4. Reduce starting load.\n5. Re-measure inrush.",
         "Starting current is reduced within device limits and voltage dip is acceptable."),
        (16, "Balance Mechanical Load",
         "Clamp meter, torque measurement tool, inspection mirror, hand tools.",
         "Lock out power before inspecting driven equipment. Use guards on test runs.",
         "1. Monitor current and torque over a cycle.\n2. Inspect the driven load for unevenness.\n3. Clear blockages.\n4. Repair the coupling.\n5. Verify steady current.",
         "Load is balanced and current and vibration remain steady through the cycle."),
        (17, "Secure Mounting Base",
         "Torque wrench, feeler gauges, shims, grout, level.",
         "Lock out and tag out. Support the machine before loosening bolts. Wear eye protection.",
         "1. Check bolt torque and base flatness.\n2. Inspect for cracks and fretting.\n3. Correct soft foot with shims.\n4. Repair or regrout the base.\n5. Retorque and re-measure.",
         "The base is rigid, fasteners hold torque, and vibration from looseness is gone."),
        (18, "Repair Rotor Bars",
         "Current signature analyzer, growler, inspection tools, replacement rotor.",
         "De-energize and lock out. Support rotor weight during removal. Use PPE.",
         "1. Run current signature analysis.\n2. Inspect bars and end rings.\n3. Repair or replace the rotor.\n4. Reduce heavy start frequency.\n5. Verify clean signature.",
         "Pole-pass sidebands are eliminated and rated torque is restored."),
        (19, "Replace Contactor",
         "Screwdriver set, multimeter, replacement contactor, wiring diagram.",
         "Lock out and tag out. Verify zero voltage. Label wires before disconnection.",
         "1. Inspect contacts for pitting.\n2. Measure coil voltage and resistance.\n3. Replace the contactor.\n4. Verify all poles close.\n5. Test motor energization.",
         "All poles close cleanly with no chatter and the motor energizes reliably."),
        (20, "Cool Overheating Bearing",
         "IR thermometer, vibration analyzer, grease gun, alignment tool.",
         "Lock out power. Allow cool-down before contact. Use insulated gloves and eye protection.",
         "1. Trend the bearing temperature.\n2. Check alignment and lubrication.\n3. Relieve excess preload.\n4. Replace the damaged bearing.\n5. Verify stable temperature.",
         "Bearing temperature stabilizes in the normal range with acceptable vibration."),
    ]
}
